spring.application.name=api-gateway

server.port=8080



# OAuth2 Authorization Server Client
spring.security.oauth2.authorizationserver.client.eventsphere-client.registration.client-id=eventsphere-client
spring.security.oauth2.authorizationserver.client.eventsphere-client.registration.client-secret={noop}eventsphere-secret
spring.security.oauth2.authorizationserver.client.eventsphere-client.registration.client-authentication-methods[0]=client_secret_basic
spring.security.oauth2.authorizationserver.client.eventsphere-client.registration.authorization-grant-types[0]=client_credentials
spring.security.oauth2.authorizationserver.client.eventsphere-client.registration.scopes[0]=events.read
spring.security.oauth2.authorizationserver.client.eventsphere-client.registration.scopes[1]=events.write