spring.application.name=api-gateway

server.port=8080


# OAuth2 Authorization Server Client
spring.security.oauth2.authorizationserver.client.eventsphere-client.registration.client-id=eventsphere-client
spring.security.oauth2.authorizationserver.client.eventsphere-client.registration.client-secret={noop}eventsphere-secret
spring.security.oauth2.authorizationserver.client.eventsphere-client.registration.client-authentication-methods[0]=client_secret_basic
spring.security.oauth2.authorizationserver.client.eventsphere-client.registration.authorization-grant-types[0]=client_credentials

# Event Service Scopes
spring.security.oauth2.authorizationserver.client.eventsphere-client.registration.scopes[0]=events.read
spring.security.oauth2.authorizationserver.client.eventsphere-client.registration.scopes[1]=events.write

# Booking Service Scopes
spring.security.oauth2.authorizationserver.client.eventsphere-client.registration.scopes[2]=bookings.read
spring.security.oauth2.authorizationserver.client.eventsphere-client.registration.scopes[3]=bookings.write

# Ticket Service Scopes
spring.security.oauth2.authorizationserver.client.eventsphere-client.registration.scopes[4]=tickets.read
spring.security.oauth2.authorizationserver.client.eventsphere-client.registration.scopes[5]=tickets.write

spring.security.oauth2.authorizationserver.client.eventsphere-client.token.access-token-time-to-live=12h